[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "fo_cavity_sim"
version = "1.0.1"
description = "Fourier optics cavity simulation tools"
authors = [{ name = "Helmut Hörner" }]
